services:

  email-server-app:
    build:
      context: .
    container_name: email_server_app
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5433/email_server
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
    depends_on:
      - postgres
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: email_server
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network

  flyway:
    image: flyway/flyway
    container_name: flyway
    environment:
      FLYWAY_USER: admin
      FLYWAY_PASSWORD: secret
    volumes:
      - ./sql:/flyway/sql
    command: -url=jdbc:postgresql://postgres:5433/email_server -connectRetries=60 migrate -X
    depends_on:
      - postgres
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network: